export class SolutionSet {
    solutionPV:number
    spouseAretirementSolutionDate:Date
    spouseAretirementSolutionAmount:number
    spouseAretirementSolutionAgeYears:number
    spouseAretirementSolutionAgeMonths:number
    spouseBretirementSolutionDate:Date
    spouseBretirementSolutionAmount:number
    spouseBretirementSolutionAgeYears:number
    spouseBretirementSolutionAgeMonths:number
    spouseAspousalSolutionDate:Date
    spouseAspousalSolutionAmount:number
    spouseAspousalSolutionAgeYears:number
    spouseAspousalSolutionAgeMonths:number
    spouseBspousalSolutionDate:Date
    spouseBspousalSolutionAmount:number
    spouseBspousalSolutionAgeYears:number
    spouseBspousalSolutionAgeMonths:number
  }